const sqlite3 = require("sqlite3").verbose();
const book = require("../objects/book"); 
const user = require("../objects/user");
var db = new sqlite3.Database("../database/books.db", (err) => {
    if (err) {
        
        return console.error(err.message);
    }
    console.log("connection successful");
})

// add all starting books to database
booksArray = [
    new book(1,
        "The Circle",
        "https://upload.wikimedia.org/wikipedia/en/2/28/The_Circle_%28Dave_Eggers_novel_-_cover_art%29.jpg?20140811060221",
        "David Eggers",
        "\"The Circle,\" is a gripping tale set in a near-future Silicon Valley, where the power and influence of technology corporations reign supreme. The narrative revolves around Mae Holland, a young and ambitious woman who secures a coveted position at The Circle, a fictional tech company reminiscent of Google or Facebook. As Mae delves deeper into her role, she becomes increasingly enmeshed in the company's culture of transparency and surveillance, blurring the lines between her professional and personal life. Eggers skillfully navigates themes of privacy, ethics, and the consequences of unchecked technological advancement, offering readers a thought-provoking exploration of the perils of a hyper-connected world.",
        1993,
        "Knopf",
        "Thriller",
        5),
    new book(2,
        "A HeartBreaking Work of Staggering Genius",
        "https://upload.wikimedia.org/wikipedia/en/6/66/Heartbreaking_Work_Dave_Eggers.jpg"
        ,"David Eggers",
        "This memoir, detailing the challenges Eggers faced after the death of both of his parents, thrust him into the literary spotlight. The book is notable for its inventive style and emotional depth, blending humor and pathos as it explores themes of family, grief, and the burdens of responsibility.",
        2000,
        "Simon & Schuster",
        "Memoir",
        5),
    //source: https://www.goodreads.com/list/show/9785.50_books_to_read_before_you_die
    new book(3, 
        "To Kill a Mockingbird",
        "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1553383690i/2657.jpg",
        "Harper Lee",
        "The unforgettable novel of a childhood in a sleepy Southern town and the crisis of conscience that rocked it. \"To Kill A Mockingbird\" became both an instant bestseller and a critical success when it was first published in 1960. It went on to win the Pulitzer Prize in 1961 and was later made into an Academy Award-winning film, also a classic. Compassionate, dramatic, and deeply moving, \"To Kill A Mockingbird\" takes readers to the roots of human behavior - to innocence and experience, kindness and cruelty, love and hatred, humor and pathos. Now with over 18 million copies in print and translated into forty languages, this regional story by a young Alabama woman claims universal appeal. Harper Lee always considered her book to be a simple love story. Today it is regarded as a masterpiece of American literature.",
        1960,
        "J. B. Lippincott & Co.",
        "Classics",
        6),
    new book(4, 
        "1984",
        "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1348990566i/5470.jpg",
        "George Orwell",
        "The year 1984 has come and gone, but George Orwell's prophetic, nightmarish vision in 1949 of the world we were becoming is timelier than ever. 1984 is still the great modern classic of \"negative utopia\"—a startlingly original and haunting novel that creates an imaginary world that is completely convincing, from the first sentence to the last four words. No one can deny the novel's hold on the imaginations of whole generations, or the power of its admonitions—a power that seems to grow, not lessen, with the passage of time.",
        1949,
        "Secker & Warburg",
        "Classics",
        4),
    new book(5,
        "The Great Gatsby",
        "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1490528560i/4671.jpg",
        "F. Scott Fitzgerald",
        "The Great Gatsby, F. Scott Fitzgerald's third book, stands as the supreme achievement of his career. This exemplary novel of the Jazz Age has been acclaimed by generations of readers. The story of the fabulously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan, of lavish parties on Long Island at a time when The New York Times noted \"gin was the national drink and sex the national obsession,\" it is an exquisitely crafted tale of America in the 1920s.",
        1925,
        "Charles Scribner's Sons",
        "Classics",
        5),
    new book(6,
        "Holy Bible: New International Version",
        "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1631965680i/280111.jpg",
        "Anonymous",
        "The New International Version is the world's most popular Bible in modern English and is renowned for its combination of accuracy and clarity of language.",
        1455,
        "Biblica",
        "Christian",
        10),
    new book(7,
        "Pride and Prejudice",
        "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1320399351i/1885.jpg",
        "Jane Austen",
        "Since its immediate success in 1813, Pride and Prejudice has remained one of the most popular novels in the English language. Jane Austen called this brilliant work \"her own darling child\" and its vivacious heroine, Elizabeth Bennet, \"as delightful a creature as ever appeared in print.\" The romantic clash between the opinionated Elizabeth and her proud beau, Mr. Darcy, is a splendid performance of civilized sparring. And Jane Austen's radiant wit sparkles as her characters dance a delicate quadrille of flirtation and intrigue, making this book the most superb comedy of manners of Regency England.",
        1813,
        "T. Egerton, Whitehall",
        "Classics",
        2),
    new book(8,
        "The Lord of the Rings",
        "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1566425108i/33.jpg",
        "J.R.R. Tolkien",
        "One Ring to rule them all, One Ring to find them, One Ring to bring them all and in the darkness bind them. In ancient times the Rings of Power were crafted by the Elven-smiths, and Sauron, the Dark Lord, forged the One Ring, filling it with his own power so that he could rule all others. But the One Ring was taken from him, and though he sought it throughout Middle-earth, it remained lost to him. After many ages it fell by chance into the hands of the hobbit Bilbo Baggins. From Sauron's fastness in the Dark Tower of Mordor, his power spread far and wide. Sauron gathered all the Great Rings to him, but always he searched for the One Ring that would complete his dominion. When Bilbo reached his eleventy-first birthday he disappeared, bequeathing to his young cousin Frodo the Ruling Ring and a perilous quest: to journey across Middle-earth, deep into the shadow of the Dark Lord, and destroy the Ring by casting it into the Cracks of Doom. The Lord of the Rings tells of the great quest undertaken by Frodo and the Fellowship of the Ring: Gandalf the Wizard; the hobbits Merry, Pippin, and Sam; Gimli the Dwarf; Legolas the Elf; Boromir of Gondor; and a tall, mysterious stranger called Strider.",
        1954,
        "Houghton Mifflin Harcourt",
        "Fantasy",
        6),
    new book(9,
        "Alice in Wonderland",
        "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1391458382i/13023.jpg",
        "Lewis Carroll, adapted by Jane Carruth",
        "Alice's Adventures in Wonderland (commonly shortened to Alice in Wonderland) is an 1865 novel written by English mathematician Charles Lutwidge Dodgson under the pseudonym Lewis Carroll. It tells of a girl named Alice falling through a rabbit hole into a fantasy world populated by peculiar, anthropomorphic creatures. The tale plays with logic, giving the story lasting popularity with adults as well as with children. It is considered to be one of the best examples of the literary nonsense genre. Its narrative course and structure, characters and imagery have been enormously influential in both popular culture and literature, especially in the fantasy genre.",
        1865,
        "Gramercy",
        "Classics",
        1),
    new book(10,
        "The Catcher in the Rye",
        "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1398034300i/5107.jpg",
        "J.D. Salinger",
        "It's Christmas time and Holden Caulfield has just been expelled from yet another school... Fleeing the crooks at Pencey Prep, he pinballs around New York City seeking solace in fleeting encounters—shooting the bull with strangers in dive hotels, wandering alone round Central Park, getting beaten up by pimps and cut down by erstwhile girlfriends. The city is beautiful and terrible, in all its neon loneliness and seedy glamour, its mingled sense of possibility and emptiness. Holden passes through it like a ghost, thinking always of his kid sister Phoebe, the only person who really understands him, and his determination to escape the phonies and find a life of true meaning. The Catcher in the Rye is an all-time classic in coming-of-age literature- an elegy to teenage alienation, capturing the deeply human need for connection and the bewildering sense of loss as we leave childhood behind.",
        1951,
        "Back Bay Books",
        "Classics",
        3),
    //source: https://www.goodreads.com/list/show/5053.The_best_Dutch_literature
    new book(11, 
        "The Discovery of Heaven",
        "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1338717776i/88389.jpg",
        "Harry Mulisch",
        "The Discovery of Heaven begins with the meeting of Onno and Max, two complicated individuals whom fate has mysteriously and magically brought together, They share responsibility for the birth of a remarkable and radiant boy who embarks on a mandated quest that takes the reader all over Europe and to the land where all such quests begin and end. Abounding in philosophical, psychological and theological inquiries - yet laced with humour that is as infectious as it is wilful - The Discovery of Heaven convinces us that it just might be possible to bring order into the chaos of the world through a story.",
        1992,
        "Penguin Books",
        "Dutch Literature",
        1),
    new book(12,
        "De Donkere Kamer van Damokles",
        "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1369861055i/1029082.jpg",
        "Willem Fredrik Hermans",
        //Description was translated by openai's chatGPT
        "De Donkere Kamer of Damokles tells the story of Henri Osewoudt, a cigar merchant from Voorschoten. During World War II, he meets a resistance fighter named Dorbeck, who looks just like him except for having black hair while Osewoudt is blond, and who gives him orders that he willingly carries out. After the occupation, everything seems to turn against him, and he is labeled a fantasist and a traitor. He desperately tries to prove otherwise.",
        1958,
        "Van Oorschot",
        "Dutch Literature",
        2),
    new book(13,
        "De Avonden",
        "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1270388843i/1380834.jpg",
        "Gerard Reve",
        //Description was translated by openai's chatGPT
        "De Avonden  tells the story of Frits van Egters, who, in the dark December days just after World War II, tries to find his way with his parents and friends. A grey haze of melancholy covers everything, and with his distinctive sense of humor, he attempts to break through the armor of boredom. In the moving final chapter, he reaches a cathartic realization that by watching and observing, he has overcome meaninglessness: 'It has been seen, it has not gone unnoticed.'",
        1947,
        "De Bezige Bij",
        "Dutch Literature",
        1),
    new book(14,
        "Een Schitterend Gebrek",
        "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1352281422i/1816082.jpg",
        "Arthur Japin",
         //Description was translated by openai's chatGPT
        "In his memoirs, Casanova casually mentions that Lucia is one of the few women he has ever wronged. But how? What really happened? Why did Lucia forsake her happiness? \"In Lucia's Eyes\" is her story, the account of an extraordinary life.",
        2003,
        "De Arbeiderspers",
        "Dutch Literature",
        3),
    new book(15,
        "Het Diner",
        "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1235217003i/6279562.jpg",
        "Herman Koch",
        //Description was translated by openai's chatGPT
        "Two couples go out for dinner at a restaurant, discussing everyday topics like work, recent movies, the war in Iraq, and vacation plans, while carefully avoiding the main issue they should be addressing: their children. The two fifteen-year-old sons of the couples, Michel and Rick, have committed an act that could ruin their futures. So far, only blurry images of them have appeared on a crime investigation TV show, and the search for their identities is at a standstill. But for how long? Two men, two women, two sons—who will dare to make a decision about the future of their own child? Complicating matters further, the father of one of the boys is the prospective new Prime Minister of the Netherlands.",
        2009,
        "Anthos",
        "Dutch Literature",
        2),
    new book(16,
        "Turks Fruit",
        "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1241777087i/1451403.jpg",
        "Jan Wolkers",
        //Description was translated by openai's chatGPT
        "Turks Fruit is the intense story of the tumultuous and ultimately tragic love between Olga and the sculptor Eric, first published in 1969. It significantly impacted Dutch literature, vividly exploring themes of love and personal connection.",
        1969,
        "Meulenhoff",
        "Dutch Literature",
        5),
    new book(17,
       "Joe Speedboot",
        "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1339751611i/1086389.jpg",
        "Tommy Wieringa",
        //Description was translated by openai's chatGPT
        "Joe Speedboot is a novel about love and rivalry, a savior without promises, and a heroic odyssey. It depicts the fate of newcomers in a Dutch village burdened by its unresolved past. The tragicomic whirlwind of events brings unexpected dynamics to the sleepy village, from which it will never recover. Tommy Wieringa has crafted a spirited, engaging coming-of-age story, featuring the boundless imagination of one man, Fransje Hermans. After an accident, Fransje becomes disabled and permanently loses his ability to speak. He appoints himself the chronicler of his village, Lomark. His fascination with newcomer Joe Speedboat is limitless: Joe, who chose his own name and by fifteen is a bomb-maker, airplane builder, and philosopher of movement. Fransje closely observes another newcomer disrupting the village's natural order—Joe's stepfather, Papa Afrika, a gentle Nubian with gazelle-like eyes who starts a small shipyard by the Rhine. Then appears the mysterious Picolien Jane, a stunning South African beauty, to whom Fransje dedicates his chronicles, risking lifelong friendships. In her, all stories converge with fatal consequences. Tommy Wieringa cleverly narrates the course of history, showing that no one can escape their destiny.",
        2005,
        "De Bezige Bij",
        "Dutch Literature",
        2),
    new book(18,
       "Hersenschimmen",
       "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1325536537i/1076175.jpg",
       "J. Bernlef", 
        //Description was translated by openai's chatGPT
       "Maarten Klein is slowly losing his grip on reality. He can no longer distinguish between the present and the past, suddenly wants to go back to work, and mistakes his wife for a stranger. \"Behind me in the doorway stands a woman. Her brown hair falls in a lock slanted to the right across her forehead. [...] She is watching me.\" More than just a story about dementia, Hersenschimmen is a love story with an inevitably tragic ending.",
       1984,
       "Querido",
       "Dutch Literature",
       1),
    new book(19,
        "Het Huis van de Moskee",
        "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1392746004i/1877062.jpg",
        "Kader Abdolah",
        //Description was translated by openai's chatGPT  
        "Aga Djan's family has been the most prominent in the Iranian city of Senedjan for centuries. They live next to the Djomè mosque, the city's largest mosque where Friday prayers are held. Generation after generation, the mosque's imam has come from Aga Djan's family; at the start of the story, it is his cousin Alsaberi. As a carpet seller, Aga Djan also leads the bazaar and holds economic power. In this novel, Kader Abdolah explores the history of Iran by focusing on how events affect this family. As the revolution brews and erupts, society is strained, and the family gradually loses all their influence and security.",
        2005,
        "De Geus",
        "Dutch Literature",
        3),
    new book(20,
        "Max Havelaar, or the Coffee Auctions of the Dutch Trading Company",
        "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1463255046i/326280.jpg",
        "Multatuli",
        "Max Havelaar - a Dutch civil servant in Java - burns with an insatiable desire to end the ill treatment and oppression inflicted on the native peoples by the colonial administration. Max is an inspirational figure, but he is also a flawed idealist whose vow to protect the Javanese from cruelty ends in his own downfall. In Max Havelaar, Multatuli (the pseudonym for Eduard Douwes Dekker) vividly recreated his own experiences in Java and tellingly depicts the hypocrisy of those who gained from the corrupt coffee trade. Sending shockwaves through the Dutch nation when it was published in 1860, this damning exposé of the terrible conditions in the colonies led to welfare reforms in Java and continues to inspire the fairtrade movement today. Roy Edwards's vibrant translation conveys the satirical and innovative style of Multatuli's autobiographical polemic. In his introduction, R. P. Meijer discusses the author's tempestuous life and career, the controversy the novel aroused and its unusual narrative structure.",
        1860,
        "Penguin Classics",
        "Classics",
        4),
    //source: https://www.goodreads.com/list/show/514.Best_Action_Adventure_Novels
    new book(21,
        "The Hobbit",
        "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1546071216i/5907.jpg",
        "J.R.R. Tolkien",
        "In a hole in the ground there lived a hobbit. Not a nasty, dirty, wet hole, filled with the ends of worms and an oozy smell, nor yet a dry, bare, sandy hole with nothing in it to sit down on or to eat: it was a hobbit-hole, and that means comfort. Written for J.R.R. Tolkien’s own children, The Hobbit met with instant critical acclaim when it was first published in 1937. Now recognized as a timeless classic, this introduction to the hobbit Bilbo Baggins, the wizard Gandalf, Gollum, and the spectacular world of Middle-earth recounts of the adventures of a reluctant hero, a powerful and dangerous ring, and the cruel dragon Smaug the Magnificent.",
        1937,
        "Houghton Mifflin",
        "Fantasy",
        7),
    new book(22,
        "The Hunger Games",
        "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1586722975i/2767052.jpg",
        "Suzanne Collins",
        "Could you survive on your own in the wild, with every one out to make sure you don't live to see the morning? In the ruins of a place once known as North America lies the nation of Panem, a shining Capitol surrounded by twelve outlying districts. The Capitol is harsh and cruel and keeps the districts in line by forcing them all to send one boy and one girl between the ages of twelve and eighteen to participate in the annual Hunger Games, a fight to the death on live TV. Sixteen-year-old Katniss Everdeen, who lives alone with her mother and younger sister, regards it as a death sentence when she steps forward to take her sister's place in the Games. But Katniss has been close to dead before—and survival, for her, is second nature. Without really meaning to, she becomes a contender. But if she is to win, she will have to start making choices that weight survival against humanity and life against love.",
        2008,
        "Scholastic Press",
        "Young Adult",
        11),
    new book(23,
        "The Hunger Games: Catching Fire",
        "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1586722941i/6148028.jpg",
        "Suzanne Collins",
        "Against all odds, Katniss Everdeen has won the Hunger Games. She and fellow District 12 tribute Peeta Mellark are miraculously still alive. Katniss should be relieved, happy even. After all, she has returned to her family and her longtime friend, Gale. Yet nothing is the way Katniss wishes it to be. Gale holds her at an icy distance. Peeta has turned his back on her completely. And there are whispers of a rebellion against the Capitol—a rebellion that Katniss and Peeta may have helped create. Much to her shock, Katniss has fueled an unrest that she's afraid she cannot stop. And what scares her even more is that she's not entirely convinced she should try. As time draws near for Katniss and Peeta to visit the districts on the Capitol's cruel Victory Tour, the stakes are higher than ever. If they can't prove, without a shadow of a doubt, that they are lost in their love for each other, the consequences will be horrifying. In Catching Fire, the second novel of the Hunger Games trilogy, Suzanne Collins continues the story of Katniss Everdeen, testing her more than ever before . . . and surprising readers at every turn.",
        2009,
        "Scholastic Press",
        "Young Adult",
        5),
    new book(24,
        "The Hunger Games: Mockingjay",
        "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1586722918i/7260188.jpg",
        "Suzanne Collins",
        "Katniss Everdeen, girl on fire, has survived, even though her home has been destroyed. Gale has escaped. Katniss's family is safe. Peeta has been captured by the Capitol. District 13 really does exist. There are rebels. There are new leaders. A revolution is unfolding. It is by design that Katniss was rescued from the arena in the cruel and haunting Quarter Quell, and it is by design that she has long been part of the revolution without knowing it. District 13 has come out of the shadows and is plotting to overthrow the Capitol. Everyone, it seems, has had a hand in the carefully laid plans—except Katniss. The success of the rebellion hinges on Katniss's willingness to be a pawn, to accept responsibility for countless lives, and to change the course of the future of Panem. To do this, she must put aside her feelings of anger and distrust. She must become the rebels' Mockingjay—no matter what the personal cost.",
        2010,
        "Scholastic Press",
        "Young Adult",
        4),
    new book(25,
        "The Da Vinci Code",
        "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1579621267i/968.jpg",
        "Dan Brown",
        "While in Paris, Harvard symbologist Robert Langdon is awakened by a phone call in the dead of the night. The elderly curator of the Louvre has been murdered inside the museum, his body covered in baffling symbols. As Langdon and gifted French cryptologist Sophie Neveu sort through the bizarre riddles, they are stunned to discover a trail of clues hidden in the works of Leonardo da Vinci—clues visible for all to see and yet ingeniously disguised by the painter. Even more startling, the late curator was involved in the Priory of Sion—a secret society whose members included Sir Isaac Newton, Victor Hugo, and Da Vinci—and he guarded a breathtaking historical secret. Unless Langdon and Neveu can decipher the labyrinthine puzzle—while avoiding the faceless adversary who shadows their every move—the explosive, ancient truth will be lost forever.",
        2003,
        "Anchor",
        "Mystery",
        12),
    new book(26, 
        "The Hunt for Red October",
        "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1281995542i/19691.jpg",
        "Tom Clancy",
        "Here is the runaway bestseller that launched Tom Clancy's phenomenal career. A military thriller so gripping in its action and so convincing in its accuracy that the author was rumored to have been debriefed by the White House. Its theme: the greatest espionage coup in history. Its story: the chase for a top secret Russian missile sub. Lauded by the Washington Post as breathlessly exciting. The Hunt for Red October remains a masterpiece of military fiction by one of the world's most popular authors, a man whose shockingly realistic scenarios continue to hold us in thrall. Somewhere under the Atlantic, a Soviet sub commander has just made a fateful decision. The Red October is heading west. The Americans want her. The Russians want her back. And the most incredible chase in history is on...",
        1984,
        "Berkley Trade",
        "Thriller",
        2),
    new book(27,
        "A Game of Thrones",
        "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1518078493i/6421982.jpg",
        "George R.R. Martin",
        "Long ago, in a time forgotten, a preternatural event threw the seasons out of balance. In a land where summers can last decades and winters a lifetime, trouble is brewing. The cold is returning, and in the frozen wastes to the north of Winterfell, sinister forces are massing beyond the kingdom’s protective Wall. To the south, the king’s powers are failing—his most trusted adviser dead under mysterious circumstances and his enemies emerging from the shadows of the throne. At the center of the conflict lie the Starks of Winterfell, a family as harsh and unyielding as the frozen land they were born to. Now Lord Eddard Stark is reluctantly summoned to serve as the king’s new Hand, an appointment that threatens to sunder not only his family but the kingdom itself. Sweeping from a harsh land of cold to a summertime kingdom of epicurean plenty, A Game of Thrones tells a tale of lords and ladies, soldiers and sorcerers, assassins and bastards, who come together in a time of grim omens. Here an enigmatic band of warriors bear swords of no human metal; a tribe of fierce wildlings carry men off into madness; a cruel young dragon prince barters his sister to win back his throne; a child is lost in the twilight between life and death; and a determined woman undertakes a treacherous journey to protect all she holds dear. Amid plots and counter-plots, tragedy and betrayal, victory and terror, allies and enemies, the fate of the Starks hangs perilously in the balance, as each side endeavors to win that deadliest of conflicts: the game of thrones. Unparalleled in scope and execution, A Game of Thrones is one of those rare reading experiences that catch you up from the opening pages, won’t let you go until the end, and leave you yearning for more.",
        1996,
        "Bantam",
        "Fantasy",
        4),
    new book(28,
        "Shutter Island",
        "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1329269081i/21686.jpg",
        "Dennis Lehane",
        "The year is 1954. U.S. Marshal Teddy Daniels and his new partner, Chuck Aule, have come to Shutter Island, home of Ashecliffe Hospital for the Criminally Insane, to investigate the disappearance of a patient. Multiple murderess Rachel Solando is loose somewhere on this remote and barren island, despite having been kept in a locked cell under constant surveillance. As a killer hurricane relentlessly bears down on them, a strange case takes on even darker, more sinister shades—with hints of radical experimentation, horrifying surgeries, and lethal countermoves made in the cause of a covert shadow war. No one is going to escape Shutter Island unscathed, because nothing at Ashecliffe Hospital is what it seems. But then neither is Teddy Daniels.",
        2003,
        "HarperTorch",
        "Mystery",
        2),
    new book(29,
        "The Odyssey",
        "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1711957706i/1381.jpg",
        "Homer",
        "Sing to me of the man, Muse, the man of twists and turns driven time and again off course, once he had plundered the hallowed heights of Troy. So begins Robert Fagles' magnificent translation of the Odyssey. If the Iliad is the world's greatest war epic, then the Odyssey is literature's grandest evocation of everyman's journey though life. Odysseus' reliance on his wit and wiliness for survival in his encounters with divine and natural forces, during his ten-year voyage home to Ithaca after the Trojan War, is at once a timeless human story and an individual test of moral endurance. In the myths and legends that are retold here, Fagles has captured the energy and poetry of Homer's original in a bold, contemporary idiom, and given us an Odyssey to read aloud, to savor, and to treasure for its sheer lyrical mastery. Renowned classicist Bernard Knox's superb Introduction and textual commentary provide new insights and background information for the general reader and scholar alike, intensifying the strength of Fagles' translation. This is an Odyssey to delight both the classicist and the public at large, and to captivate a new generation of Homer's students.",
        701,
        "Penguin Classics",
        "Classics",
        7),
    new book(30,
        "Jurassic Park",
        "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1529604411i/40604658.jpg",
        "Michael Crichton",
        "An astonishing technique for recovering and cloning dinosaur DNA has been discovered. Now humankind’s most thrilling fantasies have come true. Creatures extinct for eons roam Jurassic Park with their awesome presence and profound mystery, and all the world can visit them—for a price. Until something goes wrong. . . . In Jurassic Park, Michael Crichton taps all his mesmerizing talent and scientific brilliance to create his most electrifying technothriller.",
        1990,
        "Ballantine Books",
        "Science Fiction",
        1),
    //Harry potter books. Source: https://www.goodreads.com/series/45175-harry-potter
    new book(31, 
        "Harry Potter and the Sorcerer's Stone",
        "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1598823299i/42844155.jpg",
        "J.K. Rowling",
        "\"Turning the envelope over, his hand trembling, Harry saw a purple wax seal bearing a coat of arms; a lion, an eagle, a badger and a snake surrounding a large letter 'H'.\" Harry Potter has never even heard of Hogwarts when the letters start dropping on the doormat at number four, Privet Drive. Addressed in green ink on yellowish parchment with a purple seal, they are swiftly confiscated by his grisly aunt and uncle. Then, on Harry's eleventh birthday, a great beetle-eyed giant of a man called Rubeus Hagrid bursts in with some astonishing news: Harry Potter is a wizard, and he has a place at Hogwarts School of Witchcraft and Wizardry. An incredible adventure is about to begin!",
        1997,
        "Pottermore Publishing",
        "Fantasy",
        15),
    new book(32, 
        "Harry Potter and the Chamber of Secrets",
        "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1474169725i/15881.jpg",
        "J.K. Rowling",
        "Ever since Harry Potter had come home for the summer, the Dursleys had been so mean and hideous that all Harry wanted was to get back to the Hogwarts School for Witchcraft and Wizardry. But just as he’s packing his bags, Harry receives a warning from a strange impish creature who says that if Harry returns to Hogwarts, disaster will strike. And strike it does. For in Harry’s second year at Hogwarts, fresh torments and horrors arise, including an outrageously stuck-up new professor and a spirit who haunts the girls’ bathroom. But then the real trouble begins – someone is turning Hogwarts students to stone. Could it be Draco Malfoy, a more poisonous rival than ever? Could it possibly be Hagrid, whose mysterious past is finally told? Or could it be the one everyone at Hogwarts most suspects… Harry Potter himself!",
        1998,
        "Arthur A. Levine Books",
        "Fantasy",
        11),
    new book(33, 
        "Harry Potter and the Prisoner of Azkaban",
        "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1630547330i/5.jpg",
        "Harry Potter, along with his best friends, Ron and Hermione, is about to start his third year at Hogwarts School of Witchcraft and Wizardry. Harry can't wait to get back to school after the summer holidays. (Who wouldn't if they lived with the horrible Dursleys?) But when Harry gets to Hogwarts, the atmosphere is tense. There's an escaped mass murderer on the loose, and the sinister prison guards of Azkaban have been called in to guard the school...",
        1999,
        "Scholastic Inc.",
        "Fantasy",
        12),
    new book(34, 
        "Harry Potter and the Goblet of Fire",
        "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1554006152i/6.jpg",
        "It is the summer holidays and soon Harry Potter will be starting his fourth year at Hogwarts School of Witchcraft and Wizardry. Harry is counting the days: there are new spells to be learnt, more Quidditch to be played, and Hogwarts castle to continue exploring. But Harry needs to be careful - there are unexpected dangers lurking...",
        2000,
        "Scholastic Inc.",
        "Fantasy",
        9),    
    new book(35, 
        "Harry Potter and the Order of the Phoenix",
        "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1546910265i/2.jpg",
        "Harry Potter is about to start his fifth year at Hogwarts School of Witchcraft and Wizardry. Unlike most schoolboys, Harry never enjoys his summer holidays, but this summer is even worse than usual. The Dursleys, of course, are making his life a misery, but even his best friends, Ron and Hermione, seem to be neglecting him. Harry has had enough. He is beginning to think he must do something, anything, to change his situation, when the summer holidays come to an end in a very dramatic fashion. What Harry is about to discover in his new year at Hogwarts will turn his world upside down...",
        2003,
        "Scholastic Inc.",
        "Fantasy",
        5),    
    new book(36, 
        "Harry Potter and the Half-Blood Prince",
        "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1587697303i/1.jpg",
        "It is the middle of the summer, but there is an unseasonal mist pressing against the windowpanes. Harry Potter is waiting nervously in his bedroom at the Dursleys' house in Privet Drive for a visit from Professor Dumbledore himself. One of the last times he saw the Headmaster, he was in a fierce one-to-one duel with Lord Voldemort, and Harry can't quite believe that Professor Dumbledore will actually appear at the Dursleys' of all places. Why is the Professor coming to visit him now? What is it that cannot wait until Harry returns to Hogwarts in a few weeks' time? Harry's sixth year at Hogwarts has already got off to an unusual start, as the worlds of Muggle and magic start to intertwine...",
        2005,
        "Scholastic Inc.",
        "Fantasy",
        7),    
    new book(37, 
        "Harry Potter and the Deathly Hallows",
        "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1663805647i/136251.jpg",
        "Harry has been burdened with a dark, dangerous and seemingly impossible task: that of locating and destroying Voldemort's remaining Horcruxes. Never has Harry felt so alone, or faced a future so full of shadows. But Harry must somehow find within himself the strength to complete the task he has been given. He must leave the warmth, safety and companionship of The Burrow and follow without fear or hesitation the inexorable path laid out for him... In this final, seventh installment of the Harry Potter series, J.K. Rowling unveils in spectacular fashion the answers to the many questions that have been so eagerly awaited.",
        2007,
        "Arthur A. Levine Books",
        "Fantasy",
        8),   
    //science fiction books. Source: https://www.goodreads.com/list/show/19341.Best_Science_Fiction
    new book(38,
        "Dune",
        "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1555447414i/44767458.jpg",
        "Frank Herbert",
        "Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world where the only thing of value is the “spice” melange, a drug capable of extending life and enhancing consciousness. Coveted across the known universe, melange is a prize worth killing for... When House Atreides is betrayed, the destruction of Paul’s family will set the boy on a journey toward a destiny greater than he could ever have imagined. And as he evolves into the mysterious man known as Muad’Dib, he will bring to fruition humankind’s most ancient and unattainable dream.",
        1965,
        "Ace",
        "Science Fiction",
        3),
    new book(39, 
        "I, Robot",
        "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1609035271i/41804.jpg",
        "Isaac Asimov",
        "Isaac Asimov's I, Robot launches readers on an adventure into a not-so-distant future where man and machine , struggle to redefinelife, love, and consciousness—and where the stakes are nothing less than survival. Filled with unforgettable characters, mind-bending speculation, and nonstop action, I, Robot is a powerful reading experience from one of the master storytellers of our time. They mustn't harm a human being, they must obey human orders, and they must protect their own existence...but only so long as that doesn't violate rules one and two. With these Three Laws of Robotics, humanity embarked on perhaps its greatest adventure: the invention of the first positronic man. It was a bold new era of evolution that would open up enormous possibilities—and unforeseen risks. For the scientists who invented the earliest robots weren't content that their creations should ' remain programmed helpers, companions, and semisentient worker-machines. And soon the robots themselves; aware of their own intelligence, power, and humanity, aren't either. As humans and robots struggle to survive together—and sometimes against each other—on earth and in space, the future of both hangs in the balance. Human men and women confront robots gone mad, telepathic robots, robot politicians, and vast robotic intelligences that may already secretly control the world. And both are asking the same questions: What is human? And is humanity obsolete? In I, Robot Isaac Asimov changes forever our perception of robots, and human beings and updates the timeless myth of man's dream to play god. with all its rewards—and terrors.",
        1950,
        "Bantam Books",
        "Science Fiction",
        4),
    new book(40,
        "Ready Player One",
        "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1500930947i/9969571.jpg",
        "Ernest Cline",
        "IN THE YEAR 2044, reality is an ugly place. The only time teenage Wade Watts really feels alive is when he's jacked into the virtual utopia known as the OASIS. Wade's devoted his life to studying the puzzles hidden within this world's digital confines, puzzles that are based on their creator's obsession with the pop culture of decades past and that promise massive power and fortune to whoever can unlock them. But when Wade stumbles upon the first clue, he finds himself beset by players willing to kill to take this ultimate prize. The race is on, and if Wade's going to survive, he'll have to win—and confront the real world he's always been so desperate to escape.",
        2011,
        "Crown Publishers",
        "Science Fiction",
        1),
    new book(41,
        "The Hitchhiker’s Guide to the Galaxy",
        "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1559986152l/386162.jpg",
        "Douglas Adams",
        "Seconds before the Earth is demolished to make way for a galactic freeway, Arthur Dent is plucked off the planet by his friend Ford Prefect, a researcher for the revised edition of The Hitchhiker's Guide to the Galaxy who, for the last fifteen years, has been posing as an out-of-work actor. Together this dynamic pair begin a journey through space aided by quotes from The Hitchhiker's Guide (\"A towel is about the most massively useful thing an interstellar hitchhiker can have\") and a galaxy-full of fellow travelers: Zaphod Beeblebrox--the two-headed, three-armed ex-hippie and totally out-to-lunch president of the galaxy; Trillian, Zaphod's girlfriend (formally Tricia McMillan), whom Arthur tried to pick up at a cocktail party once upon a time zone; Marvin, a paranoid, brilliant, and chronically depressed robot; Veet Voojagig, a former graduate student who is obsessed with the disappearance of all the ballpoint pens he bought over the years. Where are these pens? Why are we born? Why do we die? Why do we spend so much time between wearing digital watches? For all the answers stick your thumb to the stars. And don't forget to bring a towel!",
        1979,
        "Del Rey",
        "Science Fiction",
        3),
    new book(42,
        "Frankenstein",
        "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1631088473i/35031085.jpg",
        "Mary Wollstonecraft Shelley",
        "Mary Shelley's seminal novel of the scientist whose creation becomes a monster. This edition is the original 1818 text, which preserves the hard-hitting and politically charged aspects of Shelley's original writing, as well as her unflinching wit and strong female voice. This edition also includes a new introduction and suggestions for further reading by author and Shelley expert Charlotte Gordon, literary excerpts and reviews selected by Gordon and a chronology and essay by preeminent Shelley scholar Charles E. Robinson.",
        1818,
        "Penguin Classics",
        "Horror",
        2),
    //detective books. Source: 
    new book(43,
        "A Study in Scarlet (Sherlock Holmes #1)",
        "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1519031842i/102868.jpg",
        "Arthur Conan Doyle",
        "Our first meeting with Sherlock Holmes. And John Watson's too! The young doctor is astonished by Holmes' many idiosyncrasies, including his talents on the violin. But it's not long before Sherlock Holmes, with Watson in tow, is working with Scotland Yard investigating the murder of two Americans whose deaths have some mysterious connection to sinister groups gathering power in both Britain and America. Here's where it all began, 'A Study in Scarlet.' Meet Sherlock Holmes, one of the world's leading consulting detectives - fictional of course!",
        1887,
        "Digireads.com",
        "Mystery",
        2),
    new book(44,
        "The Girl with the Dragon Tattoo",
        "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1684638853i/2429135.jpg",
        "Stieg Larsson",
        "Harriet Vanger, a scion of one of Sweden’s wealthiest families disappeared over forty years ago. All these years later, her aged uncle continues to seek the truth. He hires Mikael Blomkvist, a crusading journalist recently trapped by a libel conviction, to investigate. He is aided by the pierced and tattooed punk prodigy Lisbeth Salander. Together they tap into a vein of unfathomable iniquity and astonishing corruption. An international publishing sensation, Stieg Larsson’s The Girl with the Dragon Tattoo combines murder mystery, family saga, love story, and financial intrigue into one satisfyingly complex and entertainingly atmospheric novel.",
        2005,
        "Viking Canada",
        "Mystery",
        4),
    new book(45,
        "Murder on the Orient Express",
        "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1486131451i/853510.jpg",
        "Agatha Christie",
        "Just after midnight, a snowdrift stops the famous Orient Express in its tracks as it travels through the mountainous Balkans. The luxurious train is surprisingly full for the time of the year but, by the morning, it is one passenger fewer. An American tycoon lies dead in his compartment, stabbed a dozen times, his door locked from the inside. One of the passengers is none other than detective Hercule Poirot. On vacation. Isolated and with a killer on board, Poirot must identify the murderer—in case he or she decides to strike again.",
        1934,
        "HarperCollins",
        "Mystery",
        2),
    new book(46,
        "The Alienist",
        "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388256626i/40024.jpg",
        "Caleb Carr",
        "The year is 1896, the place, New York City. On a cold March night New York Times reporter John Schuyler Moore is summoned to the East River by his friend and former Harvard classmate Dr. Laszlo Kreizler, a psychologist, or \"alienist.\" On the unfinished Williamsburg Bridge, they view the horribly mutilated body of an adolescent boy, a prostitute from one of Manhattan's infamous brothels. The newly appointed police commissioner, Theodore Roosevelt, in a highly unorthodox move, enlists the two men in the murder investigation, counting on the reserved Kreizler's intellect and Moore's knowledge of New York's vast criminal underworld. They are joined by Sara Howard, a brave and determined woman who works as a secretary in the police department. Laboring in secret (for alienists, and the emerging discipline of psychology, are viewed by the public with skepticism at best), the unlikely team embarks on what is a revolutionary effort in criminology-- amassing a psychological profile of the man they're looking for based on the details of his crimes. Their dangerous quest takes them into the tortured past and twisted mind of a murderer who has killed before--and will kill again before the hunt is over. Fast-paced and gripping, infused with a historian's exactitude, The Alienist conjures up the Gilded Age and its untarnished underside: verminous tenements and opulent mansions, corrupt cops and flamboyant gangsters, shining opera houses and seamy gin mills. Here is a New York during an age when questioning society's belief that all killers are born, not made, could have unexpected and mortal consequences.",
        1994,
        "Random House",
        "Mystery",
        4),
    //new best sellers. Source: https://www.goodreads.com/shelf/show/current-bestsellers
    new book(47,
        "When the Stars Go Dark",
        "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1597950967i/54895727.jpg",
        "Paula McLain",
        "Anna Hart is a missing persons detective in San Francisco. When tragedy strikes her personal life, Anna, desperate and numb, flees to the Northern California village of Mendocino to grieve. She lived there as a child with her beloved foster parents, and now she believes it might be the only place left for her. Yet the day she arrives, she learns a local teenage girl has gone missing. The crime feels frighteningly reminiscent of the most crucial time in Anna's childhood, when the unsolved murder of a young girl touched Mendocino and changed the community forever. As past and present collide, Anna realizes that she has been led to this moment. The most difficult lessons of her life have given her insight into how victims come into contact with violent predators. As Anna becomes obsessed with the missing girl, she must accept that true courage means getting out of her own way and learning to let others in. Weaving together actual cases of missing persons, trauma theory, and a hint of the metaphysical, this propulsive and deeply affecting novel tells a story of fate, necessary redemption, and what it takes, when the worst happens, to reclaim our lives--and our faith in one another. From the New York Times bestselling author of The Paris Wife comes a novel of intertwined destinies and heart-wrenching suspense: A detective hiding away from the world. A series of disappearances that reach into her past. Can solving them help her heal?",
        2021,
        "Ballantine Books",
        "Mystery",
        2),
    new book(48,
        "Seven Days in June",
        "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1621846249i/55648820.jpg",
        "Tia Williams",
        "Brooklynite Eva Mercy is a single mom and bestselling erotica writer, who is feeling pressed from all sides. Shane Hall is a reclusive, enigmatic, award-winning literary author who, to everyone's surprise, shows up in New York. When Shane and Eva meet unexpectedly at a literary event, sparks fly, raising not only their past buried traumas, but the eyebrows of New York's Black literati. What no one knows is that twenty years earlier, teenage Eva and Shane spent one crazy, torrid week madly in love. They may be pretending that everything is fine now, but they can't deny their chemistry - or the fact that they've been secretly writing to each other in their books ever since. Over the next seven days in the middle of a steamy Brooklyn summer, Eva and Shane reconnect, but Eva's not sure how she can trust the man who broke her heart, and she needs to get him out of New York so that her life can return to normal. But before Shane disappears again, there are a few questions she needs answered... With its keen observations of Black life and the condition of modern motherhood, as well as the consequences of motherless-ness, Seven Days in June is by turns humorous, warm and deeply sensual.",
        2021,
        "Grand Central Publishing",
        "Romance",
        1),
    new book(49,
        "The Man Who Live Underground",
        "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1611776119i/53336614.jpg",
        "Richard Wright",
        "A major literary event: an explosive, previously unpublished novel from the 1940s by the legendary author of Native Son and Black Boy. Fred Daniels, a black man, is picked up randomly by the police after a brutal murder in a Chicago neighborhood and taken to the local precinct where he is tortured until he confesses to a crime he didn't commit. After signing a confession, he escapes--or is permitted to escape--from the precinct and takes up residence in the sewers below the streets of Chicago. This is the simple, horrible premise of Richard Wright's scorching novel, The Man Who Lived Underground, a masterpiece written in the same period as his landmark books Native Son (1940) and Black Boy (1945) that he was unable to publish in his lifetime. Only small parts of it have appeared in print, and in a significantly redacted form it would eventually be included in the short story collection Eight Men (1961). Now, for the first time, this incendiary novel about race and violence in America, the work that meant more to Wright than any other (\"I have never written anything in my life that stemmed more from sheer inspiration\"), is published in full, in the form that he intended.",
        1942,
        "Library of America",
        "Classics",
        2),
    //Number 50 must of course be: 
    new book(50,
        "Fifty Shades of Grey",
        "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1385207843i/10818853.jpg",
        "E.L. James",
        "When literature student Anastasia Steele goes to interview young entrepreneur Christian Grey, she encounters a man who is beautiful, brilliant, and intimidating. The unworldly, innocent Ana is startled to realize she wants this man and, despite his enigmatic reserve, finds she is desperate to get close to him. Unable to resist Ana’s quiet beauty, wit, and independent spirit, Grey admits he wants her, too—but on his own terms. Shocked yet thrilled by Grey’s singular erotic tastes, Ana hesitates. For all the trappings of success—his multinational businesses, his vast wealth, his loving family—Grey is a man tormented by demons and consumed by the need to control. When the couple embarks on a daring, passionately physical affair, Ana discovers Christian Grey’s secrets and explores her own dark desires. Erotic, amusing, and deeply moving, the Fifty Shades Trilogy is a tale that will obsess you, possess you, and stay with you forever.",
        2011,
        "Vintage",
        "Romance",
        12),
];

for (bookie of booksArray){
    bookie.addToDB();
}

// add test user to db

main()

async function main(){
}



// function selectRows() {
//     db.each('SELECT username FROM users', (error, row) => {
//       if (error) {
//         throw new Error(error.message);
//       }
//       console.log(row);
//     });
//   };
// selectRows(); 